language: python

python: 3.5

services: mysql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - sudo redis-server /etc/redis/redis.conf --port $REDIS_PORT --requirepass $REDIS_PASS
  - mysql -e "create database IF NOT EXISTS $DB_NAME CHARACTER SET utf8 COLLATE utf8_general_ci;" -uroot
  - mysql -e "create user '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'$DB_HOST' WITH GRANT OPTION;" -uroot
  - python manage.py migrate

script:
  - coverage run --source=graffiti_map,graffities manage.py test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - leonst998@gmail.com
    on_success: always
    on_failure: always